language: node_js
node_js:
  - "8"
dist: trusty
services:
  - mongodb
  - redis-server
env:
  - NODE_ENV=ci PORT=3000
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install -g firebase
  - npm install
  - npm run build
script: 
  - nohup npm run start &
  - sleep 5
  - npm run test
after_success:
  - firebase deploy --token $FIREBASE_TOKEN